version: "3.8"

volumes:
  mysql_volume:
    driver: local
networks:
  php-advanced:
    driver: bridge
services:
  mysql:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33063:3306"
    volumes:
      - "mysql_volume:/var/lib/mysql"
    networks:
      - php-advanced
  php:
    build:
      context: .docker/php
#    image: "php:8.1-apache"
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8087:80"
    networks:
      - php-advanced