FROM php:8.1-apache

RUN docker-php-ext-install -j$(nproc) pdo_mysql \
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
